# Generated by Django 5.2.8 on 2025-11-20 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intrebare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_intrebare', models.CharField(max_length=200)),
                ('data_publicare', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data publicarii')),
            ],
        ),
        migrations.CreateModel(
            name='Optiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_optiune', models.CharField(max_length=200)),
                ('voturi', models.IntegerField(default=0)),
                ('intrebare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondaje.intrebare')),
            ],
        ),
    ]
