# Generated by Django 5.2.8 on 2025-11-20 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaje', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intrebare',
            options={'verbose_name_plural': 'Intrebari'},
        ),
        migrations.AlterModelOptions(
            name='optiune',
            options={'verbose_name_plural': 'Optiuni'},
        ),
        migrations.CreateModel(
            name='Vot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrebare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondaje.intrebare')),
                ('optiune_aleasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondaje.optiune')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizator', 'intrebare')},
            },
        ),
    ]
