# Generated by Django 5.2.8 on 2025-11-20 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaje', '0002_alter_intrebare_options_alter_optiune_options_vot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='intrebare',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondaje_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intrebare',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intrebare',
            name='tip_vot',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='vot',
            name='data_vot',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data votului'),
        ),
        migrations.AddField(
            model_name='vot',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vot',
            name='utilizator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vot',
            unique_together={('session_key', 'intrebare', 'optiune_aleasa'), ('utilizator', 'intrebare', 'optiune_aleasa')},
        ),
        migrations.CreateModel(
            name='Echipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('data_creare', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data crearii')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echipe_create', to=settings.AUTH_USER_MODEL)),
                ('membri', models.ManyToManyField(blank=True, related_name='echipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Echipe',
            },
        ),
        migrations.AddField(
            model_name='intrebare',
            name='echipa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sondaje', to='sondaje.echipa'),
        ),
    ]
