# Generated by Django 5.2.8 on 2025-11-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaje', '0003_alter_vot_unique_together_intrebare_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrebare',
            name='data_expirare',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data expirarii'),
        ),
        migrations.AddField(
            model_name='intrebare',
            name='timp_limita_minute',
            field=models.IntegerField(blank=True, help_text='Lăsați gol pentru fără limită de timp', null=True, verbose_name='timp limita (minute)'),
        ),
    ]
