# Generated by Django 5.2.8 on 2025-11-21 21:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaje', '0004_intrebare_data_expirare_intrebare_timp_limita_minute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='echipa',
            name='cod_unic',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Cod unic'),
        ),
        migrations.CreateModel(
            name='CerereAlaturare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Respinsă')], default='pending', max_length=10)),
                ('data_cerere', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data cererii')),
                ('data_raspuns', models.DateTimeField(blank=True, null=True, verbose_name='data răspunsului')),
                ('echipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_alaturare', to='sondaje.echipa')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cereri_alaturare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cereri de alăturare',
                'ordering': ['-data_cerere'],
                'unique_together': {('echipa', 'utilizator')},
            },
        ),
    ]
