# Generated by Django 5.2.8 on 2025-11-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondaje', '0006_genereaza_coduri_echipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrebare',
            name='allow_free_text',
            field=models.BooleanField(default=False, help_text='Permite utilizatorilor să introducă răspunsuri libere în loc de opțiuni predefinite', verbose_name='Permite răspuns liber'),
        ),
        migrations.AddField(
            model_name='optiune',
            name='is_free_text',
            field=models.BooleanField(default=False),
        ),
    ]
